services:
  postgres:
    image: postgres:latest
    container_name: codeinsight-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: codeinsight_ai
      TZ: Asia/Kolkata
      # PGTZ: Asia/Kolkata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata: